from collections.abc import Callable, Iterable, Mapping
from typing import Protocol

from app.modules.literature.domain.models import (
    Attachment,
    AssetIntegrity,
    StagedPdf,
    Collection,
    FilterOptions,
    LibraryChanges,
    LiteratureAssets,
    LibraryState,
    Note,
    Paper,
    PaperDetail,
    PaperPage,
    ProviderFile,
)
from app.modules.literature.domain.canonical import Ingestion, IngestResult
from app.modules.literature.domain.workflow import UploadBatch, UploadItem, MetadataProposal


class LiteratureProvider(Protocol):
    name: str

    def describe_attachment(self, attachment: Attachment) -> Attachment: ...

    def get_import_item(self, identifier: str) -> LibraryChanges: ...

    @property
    def configured(self) -> bool:
        """Whether the provider has enough configuration to be used."""
        ...

    def list_collections(self) -> tuple[Collection, ...]:
        ...

    def list_papers(
        self,
        *,
        collection_id: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> PaperPage:
        ...

    def list_changes(self, *, since: str) -> LibraryChanges:
        ...

    def list_assets(self) -> LiteratureAssets:
        ...

    def open_attachment(self, attachment: Attachment, *, range_header: str | None = None) -> ProviderFile:
        ...


class LiteratureCache(Protocol):
    def get_library_state(self, *, provider: str, library_id: str) -> LibraryState | None:
        ...

    def list_collections(self) -> tuple[Collection, ...]:
        ...

    def list_papers(
        self,
        *,
        collection_id: str | None = None,
        limit: int = 50,
        offset: int = 0,
        query: str | None = None,
        author: str | None = None,
        year: int | None = None,
        journal: str | None = None,
        tag: str | None = None,
    ) -> PaperPage:
        ...

    def get_paper(self, paper_id: str) -> PaperDetail | None:
        ...

    def list_notes(self, paper_id: str) -> tuple[Note, ...]:
        ...

    def list_attachments(self, paper_id: str) -> tuple[Attachment, ...]:
        ...

    def list_filter_options(self) -> FilterOptions:
        ...

    def replace_library(
        self,
        *,
        provider: str,
        library_id: str,
        collections: Iterable[Collection],
        papers: Iterable[Paper],
        collection_papers: Mapping[str, Iterable[str]],
        notes: Iterable[Note],
        attachments: Iterable[Attachment],
        library_version: str | None,
    ) -> None:
        ...

    def apply_changes(
        self,
        *,
        provider: str,
        library_id: str,
        changes: LibraryChanges,
    ) -> None:
        ...

    def mark_sync_failed(self, *, provider: str, library_id: str, error: str) -> None:
        ...


class CanonicalLibrary(LiteratureCache, Protocol):
    def record_asset_failure(self, source: Attachment, error: str) -> bool: ...
    def asset_acquisition_state(self, source: Attachment) -> dict | None: ...
    def owned_asset(self, source: Attachment, *, require_current_source: bool = True) -> Attachment | None: ...
    def record_owned_asset(self, source: Attachment, asset: Attachment, observed: Attachment, size_bytes: int) -> Attachment: ...
    def record_ingestion_conflict(self, incoming: Ingestion, error: Exception) -> str: ...
    def ingest(self, incoming: Ingestion) -> IngestResult: ...
    def ingest_asset(self, incoming: Ingestion, asset: Attachment) -> tuple[IngestResult, Attachment]: ...
    def add_asset(self, asset: Attachment) -> Attachment: ...
    def provenance(self, paper_id: str) -> dict[str, object]: ...
    def saved_origins(self, keys: Iterable[str]) -> dict[str, str]: ...
    def set_state(self, paper_id: str, *, reading_status: str | None = None, deleted: bool | None = None, tags: Iterable[str] | None = None) -> None: ...
    def create_collection(self, name: str, parent_id: str | None = None) -> Collection: ...
    def set_membership(self, paper_id: str, collection_id: str, present: bool) -> None: ...
    def select_primary_asset(self, paper_id: str, asset_id: str) -> None: ...
    def import_selected_item(self, changes: LibraryChanges) -> IngestResult: ...


class LiteratureFileStore(Protocol):
    storage_kind: str
    def stage_source_pdf(self, chunks: Iterable[bytes], filename: str) -> StagedPdf: ...
    def inspect(self, asset: Attachment) -> AssetIntegrity: ...
    def store_pdf(self, data: bytes, filename: str) -> tuple[str, str]: ...
    def stage_pdf(self, data: bytes, filename: str) -> tuple[str, str]: ...
    def finalize_pdf(self, staging_key: str, sha256_hex: str, *, keep_staging: bool = False) -> str: ...
    def discard_staged(self, staging_key: str) -> None: ...
    def cleanup_staging(self, max_age_seconds: int = 3600, *, protected: set[str] | None = None) -> int: ...
    def open(self, asset: Attachment, *, range_header: str | None = None) -> ProviderFile: ...


class LiteratureWorkflowRepository(CanonicalLibrary, Protocol):
    def confirm_metadata(self, paper_id: str, snapshot: dict) -> dict: ...
    def create_upload_batch(self) -> UploadBatch: ...
    def get_upload_batch(self, batch_id: str) -> UploadBatch | None: ...
    def stage_upload(self, batch_id: str, create: Callable[[], UploadItem]) -> UploadItem: ...
    def update_upload(self, batch_id: str, item_id: str, metadata: dict) -> UploadItem: ...
    def confirm_upload(self, batch_id: str, item_id: str, finalize: Callable[[str, str], str], *, storage_kind: str = 'local') -> dict: ...
    def cancel_upload(self, batch_id: str, item_id: str | None = None) -> UploadBatch: ...
    def cleanup_uploads(self, cleanup: Callable[[set[str]], int]) -> int: ...
    def create_metadata_proposal(self, paper_id: str, source: str, metadata: dict) -> MetadataProposal: ...
    def get_metadata_proposal(self, proposal_id: str) -> MetadataProposal | None: ...
    def list_metadata_proposals(self, paper_id: str) -> tuple[MetadataProposal, ...]: ...
    def resolve_metadata_proposal(self, proposal_id: str, *, accept: bool, edits: dict | None = None) -> MetadataProposal: ...


class LiteratureIdentityRepository(LiteratureWorkflowRepository, Protocol):
    def identity_context(self, paper_id: str) -> dict: ...
    def list_identity_conflicts(self, *, limit: int = 100, offset: int = 0) -> dict: ...
    def review_identity(self, paper_id: str, *, snapshot: str, evidence_ids: list[str], reason: str, correction: dict | None = None) -> dict: ...
    def decide_identity_conflict(self, conflict_id: str, *, snapshot: str, decision: str, reason: str) -> dict: ...
    def link_paper_versions(self, preprint_id: str, published_id: str, *, preprint_snapshot: str, published_snapshot: str, evidence_ids: list[str], reason: str) -> dict: ...
    def retract_paper_version(self, version_id: str, *, snapshot: str, reason: str) -> dict: ...
